### ISSUE TITLE
Negate exclusion doesn't seem to work

### ISSUE THREAD

**Issue by chadhietala** [rwjblue/broccoli-funnel#12]
I'm not sure if negated exclusion works an example is something like:

```
var dist = new Funnel('dist', {
  exclude: ['*.css', '!app.css']
});
```
One would expect that all css except app.css to be removed. @stefanpenner ran into this with `rm` for broccoli-stew. See https://github.com/stefanpenner/broccoli-stew/pull/34#issuecomment-68620297 for more context.

**Comment by rwjblue** [comment]
I wouldn't think that using a second matcher to modify a prior one would work. They are all evaluated independently so the first match found while iterating wins.  This could be "solved" by making each exclusion run completely before the next starts, but that doesn't seem to be what we want either.

Consider the following:

```javascript
var dist = new Funnel('dist', {
  include: ['*.js', '*.css']
});
```

If the globs simply modified the output from one another then the above would not include both JS and CSS files.

**Comment by timmfin** [comment]
This sounds similar to why [node-glob is now deprecating negation patterns](https://github.com/isaacs/node-glob#comments-and-negation). It was just too confusing, and didn't map well to different cases, so a different API (`ignore`) is now used.

**Comment by rwjblue** [comment]
Yes, agreed.  I'm going to close this for now.  I'm willing to reopen and address if there is a reasonable solution to my prior comment's conundrum...
